### PR TITLE
Packaging/tranform into package

### PR DESCRIPTION
**Pull request by jriddy**
Someone at my organization wants to be able to use this in a project, but it's not currently set up as a pip-installable python package, nor does it have a container package to refer to it in other code. After this it's easy to install this into a virtualenv with

    $ pip install git+http://github.com/richzhang/PerceptualSimilarity.git

And then you could use it in your code as

    from perceptualsimilarity.models import dist_models

This changes that in the simplest way possible: by moving it all into a `perceptualsimilarity` directory and adding a basic `setup.py` to allow it to be installed. With a bit more metadata in `setup.py`, you could upload it to PyPI as well.

If you like this, we could also transform the scripts to entry-points that get installed on the command-line PATH when you install from PyPI as well.

### CODE REVIEW

**Comment by jriddy** [comment]
We've found some issues with the import statements in the existing code...I'll get to fixing these things soon and update this PR

**Comment by richzhang** [comment]
Thanks a lot for making the package! Was the PR fixed with changes?

**Comment by jriddy** [comment]
No I'm sorry I've been busy due to release pressure at work. There's a few
things that got broken when I changed this, but my boy Karl assures me that
he has fixes. Once I get back from vacation in a few weeks I'll get that
integrated, and I'll push my changes.

Sorry that the vicissitudes of work life keep me from following up on my
promise, but I'll get there 😉

**Comment by richzhang** [comment]
Of course I understand that. Thanks so much!

**Comment by jriddy** [comment]
Hey just saw this, I can give this another go if you're interested, but this PR was so old it was stale.

Are you still interested in making this into a pip-distributable package? So it go on PyPI and such?

**Comment by richzhang** [comment]
Hi, I finally got around to this. pip install lpips :)

**Pull request closed without merging**
