### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by wilhelmhb**
Allow the `PerceptualLoss` to be installed as a package, and reused.
#39 forces us to call `python setup.py`.
#13 has not been updated for more than a year.

The package will include the README and the weights.

I also fixed some dependencies, and cleaned a part of the code.

### CODE REVIEW

**Comment by mameli** [comment]
As long as the author has not indexed the package in PyPI, isn't the command `python setup.py install` the easiest way to install this repo? `pip install perceptual-similarity-pytorch` is not working right now
p.s. Good job on the code refactoring

**Comment by wilhelmhb** [comment]
`pip install perceptual-similarity-pytorch` is the command for installing the package *once it has been published to PyPI*.
The easiest way to install this repo is `pip install -e /path/to/repo`, from anywhere else. The `-e`options will reflect changes from the source code, thus you should not need to reinstall the repo each time you change something.

**Comment by smsegal** [comment]
@wilhelmhb  Oh darn I just redid a bunch of this packaging work on my own, I should have checked the PR's first. You haven't published to PyPi correct? I'll just be installing this from your fork then.

**Comment by wilhelmhb** [comment]
@smsegal no, I haven't published to PyPi. I wanted to let the owner of the original repo do it, as it's not my own code ;)

**Comment by richzhang** [comment]
I finally got around to making a pip install. Thanks for your PR; I added you to the readme

**Pull request closed without merging**
