### PR TITLE
Changes to allow using multiple gpus with default configuration

### PR DESCRIPTION
**Pull request by g1910**
Hi, I have made changes to the repository to allow using multiple GPUs with Perceptual Similarity implementation. Please review and let me know of any further changes.

### CODE REVIEW

**Comment by richzhang** [comment]
Thank you very much for the pull request. I followed it to add parallelization to the latest commit. I also realized that the `PNetLin` doesn't need the gpu id information and should be controlled from the dist_model class.

**Comment by g1910** [comment]
Hi Richard, thanks for incorporating the changes. I would have appreciated if you had merged my pull request directly into the code base or suggested further changes for merge so that my contribution could have been officially acknowledged. Since you went ahead and made the changes yourself, it would be nice if you could please acknowledge my contribution somewhere in the repository (perhaps in the ReadMe).

**Comment by richzhang** [comment]
I got around to cleaning things up and made a pip install. I added you to the readme

**Comment by g1910** [comment]
Thanks @richzhang! :)

**Pull request closed without merging**
